### ISSUE TITLE
Delete comment

### ISSUE THREAD

**Issue by fahriyor** [wfleming/WFInstagramAPI#1]
Hey, Will!
First of all, thanks for writing this lib and sharing it with us.
I have a question according to deleting comments, using your lib how can I delete comments? In your models I can see that comments model has only method for posting the comment. I did my custom implementation for deleting comments (see the post request below), but it does not work, returns empty data from server. Have you tried to delete comment from media using instagram API? If yes, did you succeed? 

delete comment req url: https://api.instagram.com/v1/media/[media_id]/comments?access_token=[access_token]
POST data:
--xXxBoUnDaRyxXx
Content-Disposition: form-data; name="comment_id"

[comment_id]
--xXxBoUnDaRyxXx
Content-Disposition: form-data; name="_method"

DELETE
--xXxBoUnDaRyxXx

Thanks for your time!

**Comment by wfleming** [comment]
Hi,

I never completed representing all aspects of the Instagram API in my library. I was developing the library for a personal project, and haven't had the time to complete aspects of it that weren't immediately needed, although I'd love to see it get picked up again.

Concerning your particular issue of deleting comments: it doesn't look like your request to delete the comment is properly formed. According Instagram's docs (http://instagram.com/developer/endpoints/comments/#delete_media_comments), I think you should be using an HTTP `DELETE` request, not a `POST` request with a `_method` parameter in the body (the `_method` parameter has historically been how things like Rails have gotten around the fact that a link in a web page really sends either a `GET` or `POST` request, but that's a hack not needed here). I think you also want the `comment_id` to be part of the URL: i.e. `https://api.instagram.com/v1/media/{media-id}/comments/{comment-id}?access_token=foo`: sending a `DELETE` request to just `https://api.instagram.com/v1/media/{media-id}/comments/` will, I think, delete _all_ comments on that media (though the docs are not entirely clear on that.

If you're using my library already, you can make use of the same patterns I do & write your own `-delete` method for models. Right now I think a delete method for the comment model would probably have to look something like this:

```
- (BOOL) deleteFromMedia:(WFIGMedia*)media error:(NSError* __autoreleasing*)error {
  NSString *path = [NSString stringWithFormat:@"/media/%@/comments/%@",
                    media.instagramId, self.commentId];
  WFIGResponse *response = [WFInstagramAPI delete:path];

  if ([response isError]) {
    *error = [response error];
  }

  return [response isSuccess];
}
```

Hope this is helpful to you.

**Comment by fahriyor** [comment]
Thanks Will, it works fine with the way you have explained. Instagram has to update their docs :)
